"""initial schema

Revision ID: 84ab7b3b1146
Revises: 
Create Date: 2026-07-26 14:35:11.104229

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84ab7b3b1146'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('monthly_budget_cents', sa.Integer(), nullable=True),
    sa.Column('per_request_limit_cents', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('total_spend_cents', sa.Integer(), nullable=False),
    sa.Column('total_requests', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_agent_id'), 'api_keys', ['agent_id'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_table('providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('api_key_env', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('avg_latency_ms', sa.Integer(), nullable=False),
    sa.Column('uptime_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_name'), 'providers', ['name'], unique=True)
    op.create_table('routing_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.Column('model_category', sa.String(length=50), nullable=True),
    sa.Column('max_cost_per_request_cents', sa.Integer(), nullable=True),
    sa.Column('min_quality_score', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('target_model_id', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('budget_cents', sa.Integer(), nullable=True),
    sa.Column('spend_cents', sa.Integer(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('killed_reason', sa.Text(), nullable=True),
    sa.Column('killed_at', sa.DateTime(), nullable=True),
    sa.Column('budget_reset_at', sa.DateTime(), nullable=True),
    sa.Column('alert_thresholds', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_agent_id'), 'agents', ['agent_id'], unique=True)
    op.create_index(op.f('ix_agents_api_key_id'), 'agents', ['api_key_id'], unique=False)
    op.create_table('budget_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.String(length=200), nullable=True),
    sa.Column('threshold_pct', sa.Integer(), nullable=False),
    sa.Column('spend_cents', sa.Integer(), nullable=False),
    sa.Column('budget_cents', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_alerts_api_key_id'), 'budget_alerts', ['api_key_id'], unique=False)
    op.create_table('cache_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.Column('messages_json', sa.Text(), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('token_fingerprint', sa.Text(), nullable=True),
    sa.Column('saved_cost_cents', sa.Integer(), nullable=False),
    sa.Column('saved_tokens', sa.Integer(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_hit_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cache_entries_api_key_id'), 'cache_entries', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_cache_entries_content_hash'), 'cache_entries', ['content_hash'], unique=False)
    op.create_index(op.f('ix_cache_entries_created_at'), 'cache_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_cache_entries_expires_at'), 'cache_entries', ['expires_at'], unique=False)
    op.create_index(op.f('ix_cache_entries_model_id'), 'cache_entries', ['model_id'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('tokenizer', sa.String(length=50), nullable=False),
    sa.Column('prompt_price', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('completion_price', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('cached_price', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('max_output', sa.Integer(), nullable=False),
    sa.Column('supports_streaming', sa.Boolean(), nullable=False),
    sa.Column('supports_tools', sa.Boolean(), nullable=False),
    sa.Column('supports_vision', sa.Boolean(), nullable=False),
    sa.Column('supports_json', sa.Boolean(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('speed_score', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_model_id'), 'models', ['model_id'], unique=True)
    op.create_index(op.f('ix_models_provider_id'), 'models', ['provider_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.String(length=200), nullable=True),
    sa.Column('model_requested', sa.String(length=200), nullable=False),
    sa.Column('model_served', sa.String(length=200), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cached_tokens', sa.Integer(), nullable=False),
    sa.Column('prompt_cost_cents', sa.Integer(), nullable=False),
    sa.Column('completion_cost_cents', sa.Integer(), nullable=False),
    sa.Column('total_cost_cents', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('ttft_ms', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('was_predicted', sa.Boolean(), nullable=False),
    sa.Column('prediction_error_pct', sa.Float(), nullable=True),
    sa.Column('routing_strategy', sa.String(length=50), nullable=True),
    sa.Column('was_cached', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_agent_id'), 'usage_records', ['agent_id'], unique=False)
    op.create_index(op.f('ix_usage_records_api_key_id'), 'usage_records', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_usage_records_created_at'), 'usage_records', ['created_at'], unique=False)
    op.create_table('agent_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('usage_record_id', sa.Integer(), nullable=True),
    sa.Column('cost_cents', sa.Integer(), nullable=False),
    sa.Column('parent_agent_id', sa.String(length=200), nullable=True),
    sa.Column('trace_id', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usage_record_id'], ['usage_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_events_agent_id'), 'agent_events', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_events_created_at'), 'agent_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_events_trace_id'), 'agent_events', ['trace_id'], unique=False)
    op.create_table('quality_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('signal_source', sa.String(length=20), nullable=False),
    sa.Column('usage_record_id', sa.Integer(), nullable=True),
    sa.Column('signal_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usage_record_id'], ['usage_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_scores_created_at'), 'quality_scores', ['created_at'], unique=False)
    op.create_index(op.f('ix_quality_scores_model_id'), 'quality_scores', ['model_id'], unique=False)
    op.create_index(op.f('ix_quality_scores_task_type'), 'quality_scores', ['task_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quality_scores_task_type'), table_name='quality_scores')
    op.drop_index(op.f('ix_quality_scores_model_id'), table_name='quality_scores')
    op.drop_index(op.f('ix_quality_scores_created_at'), table_name='quality_scores')
    op.drop_table('quality_scores')
    op.drop_index(op.f('ix_agent_events_trace_id'), table_name='agent_events')
    op.drop_index(op.f('ix_agent_events_created_at'), table_name='agent_events')
    op.drop_index(op.f('ix_agent_events_agent_id'), table_name='agent_events')
    op.drop_table('agent_events')
    op.drop_index(op.f('ix_usage_records_created_at'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_api_key_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_agent_id'), table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index(op.f('ix_models_provider_id'), table_name='models')
    op.drop_index(op.f('ix_models_model_id'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_cache_entries_model_id'), table_name='cache_entries')
    op.drop_index(op.f('ix_cache_entries_expires_at'), table_name='cache_entries')
    op.drop_index(op.f('ix_cache_entries_created_at'), table_name='cache_entries')
    op.drop_index(op.f('ix_cache_entries_content_hash'), table_name='cache_entries')
    op.drop_index(op.f('ix_cache_entries_api_key_id'), table_name='cache_entries')
    op.drop_table('cache_entries')
    op.drop_index(op.f('ix_budget_alerts_api_key_id'), table_name='budget_alerts')
    op.drop_table('budget_alerts')
    op.drop_index(op.f('ix_agents_api_key_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_agent_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_table('routing_rules')
    op.drop_index(op.f('ix_providers_name'), table_name='providers')
    op.drop_table('providers')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_agent_id'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
